name: Cypress Tests

on:
  pull_request:
    branches: [main]
  schedule:
    - cron: "*/10 11-23 * * *"
    - cron: "*/10 0-3 * * *"

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          spec: cypress/e2e/website.cy.js
        env:
          CYPRESS_url: ${{ secrets.CYPRESS_URL }}
